### ISSUE TITLE
Keyboard navigation broken when we open a modal + autofocus input

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/react-components#304] opened 2019-09-24 14:38 UTC
1. Open settings/subscription
2. Go to invoices
3. Use TAB + Enter to select then open the customize modal

Autofocus is inside the textarea. Close the modal via Esc the focus is lost it should be back on the customize button.

-> it's only with modal and autofocus

![output (copy)](https://user-images.githubusercontent.com/713283/65521542-b233db80-dee9-11e9-808d-a4ed4b97a89f.gif)

**Comment by mmso** [comment] 2019-09-24 15:49
Duplicate of https://github.com/ProtonMail/react-components/issues/67

**Closed by mmso** 2019-09-24 15:49 UTC
